# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 6156f16a233904cb8acd0a4cf5a19a2ac25b89acd84bb5498d80dfe3798aa3e2f3083f423e9647a8d0a44bff16a50a8f0de5bfd1f18855f7da0905f46ed239c3

test:
  secret_key_base: a3354054234c8d95a5c3b81cd981208fd84575d54079fc2075faef37af9fafbf4e583dce3cf565f4c1d1fcdb195cc071c5dbfb2dbbe61088f4d316c56c714d59

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
